[openfoam]
source = 'cmd'
cmd = """
get_latest_openfoam_version() {
  export GIT_TERMINAL_PROMPT=0
  for i in {13..40}; do
    git ls-remote "https://github.com/OpenFOAM/OpenFOAM-$i.git" &>/dev/null &&
    LATEST=$i || break
  done

  TAG_NAME="refs/tags/version-${LATEST}^{}"
  COMMIT_HASH=$(git ls-remote --tags "https://github.com/OpenFOAM/OpenFOAM-${LATEST}.git" |
    grep -F "${TAG_NAME}" |
    awk '{print $1}')

  if [ -n "$COMMIT_HASH" ]; then
    DATE=$(curl -s "https://api.github.com/repos/OpenFOAM/OpenFOAM-${LATEST}/git/commits/${COMMIT_HASH}" |
      jq -r '.committer.date' |
      cut -d'T' -f1 |
      tr -d '-')
    SHORT_HASH=$(echo "${COMMIT_HASH}" | cut -c1-7)
    LATEST_VERSION="${LATEST}.${DATE}+${SHORT_HASH}"
  else
    LATEST_TAG_INFO=$(git ls-remote --tags "https://github.com/OpenFOAM/OpenFOAM-${LATEST}.git" |
      grep -E 'refs/tags/[0-9]{8}$' |
      tail -n1)
    
    if [ -n "$LATEST_TAG_INFO" ]; then
        COMMIT_HASH=$(echo "${LATEST_TAG_INFO}" | awk '{print $1}')
        TAG_DATE=$(echo "${LATEST_TAG_INFO}" | awk '{print $2}' | sed 's|refs/tags/||')
        SHORT_HASH=$(echo "${COMMIT_HASH}" | cut -c1-7)
        LATEST_VERSION="${LATEST}.${TAG_DATE}+${SHORT_HASH}"
    else
        LATEST_VERSION=""
    fi
  fi

  echo "${LATEST_VERSION}" |
  awk '{ print $0; if ($0 !~ /^[0-9]{2}[.][0-9]{8}[+][a-f0-9]{7}$/) exit 1 }'
}

get_latest_openfoam_version
"""