[ved-git]
source="cmd"
cmd="~/nvchecker/github_version.py vlang/ved --releases"
[memos-git]
source="cmd"
cmd="~/nvchecker/github_version.py usememos/memos -strip v --releases"
[goxel-voxel-editor-git]
source="cmd"
cmd="~/nvchecker/github_version.py --releases guillaumechereau/goxel -strip v"
[kdeconnect-git]
source="cmd"
cmd="~/nvchecker/github_version.py KDE/kdeconnect-kde -strip v --tags"
[shotcut-git]
source='cmd'
cmd="~/nvchecker/github_version.py mltframework/shotcut -strip v --releases"
[hardened-malloc-git]
source="cmd"
cmd="~/nvchecker/github_version.py grapheneos/hardened_malloc --releases"
[openfortivpn-git]
source="cmd"
cmd="~/nvchecker/github_version.py adrienverge/openfortivpn --tags -strip v"
[openscad-nopscadlib-git]
source="cmd"
cmd="~/nvchecker/github_version.py nophead/NopSCADlib --tags -strip v"
[slade-git]
source="cmd"
cmd="~/nvchecker/github_version.py sirjuddington/SLADE --releases"
[rot8-git]
source="cmd"
cmd="~/nvchecker/github_version.py efernau/rot8 --releases -strip v"
[stygiansift-git]
source="cmd"
cmd="~/nvchecker/github_version.py Mauitron/StygianSift --commits"
[aircrack-ng-git]
source="cmd"
cmd="~/nvchecker/github_version.py aircrack-ng/aircrack-ng --releases"
[clamav-git]
source="cmd"
cmd="~/nvchecker/github_version.py Cisco-Talos/clamav -strip clamav- --releases"
[gnome-shell-git]
source="cmd"
cmd="~/nvchecker/github_version.py GNOME/gnome-shell --tags"
[cycle-git]
source="cmd"
cmd="~/nvchecker/github_version.py metlov/cycle --releases -strip v"
[dlib-git]
source="cmd"
cmd="~/nvchecker/github_version.py davisking/dlib --releases -strip v"
[dlib-cuda-git]
source="cmd"
cmd="~/nvchecker/github_version.py davisking/dlib --releases -strip v"
["testssl.sh-git"]
source="cmd"
cmd="~/nvchecker/github_version.py drwetter/testssl.sh --releases -strip v"
[docker-git]
source = "cmd"
cmd="~/nvchecker/github_version.py moby/moby --releases -strip v"
[hyperrogue-git]
source="cmd"
cmd="~/nvchecker/github_version.py zenorogue/hyperrogue -strip v --releases"
[remmina-git]
source="cmd"
cmd="~/nvchecker/github_version.py FreeRDP/Remmina --tags -strip v"
[montage-git]
source="cmd"
cmd="~/nvchecker/github_version.py Caltech-IPAC/Montage --tags -strip v"
