name: Request Package Build
description: Request a package to be built
title: "[BUILD REQUEST] - Please wait for auto-update"
labels: ["build-request"]
body:
  - type: markdown
    attributes:
      value: |
        Select a package to build and provide a reason. The title will be automatically updated after submission.

  - type: dropdown
    id: package_name
    attributes:
      label: Package to Build
      description: Select the package you want to build
      options:
        - waterfox-bin
        - firefox-developer-edition
        - chromium-dev
        - custom-package
      default: 0
    validations:
      required: true

  - type: input
    id: custom_package
    attributes:
      label: Custom Package Name
      description: If you selected "custom-package" above, specify the package name here
      placeholder: e.g., "my-custom-app"
    validations:
      required: false

  - type: textarea
    id: reason
    attributes:
      label: Reason for Build
      description: Why do you need this package built?
      placeholder: e.g., "Security update needed" or "New version available"
    validations:
      required: true
