name: Request Package Build
description: Request a package to be built
title: "[BUILD REQUEST] - [DON'T MODIFY THIS]"
labels: [build-request]
body:
  - type: markdown
    attributes:
      value: |
        Select a package to build and provide a reason. The title will be automatically updated after submission.

  - type: dropdown
    id: package_name
    attributes:
      label: Package to Build
      description: Select the package you want to build
      options:
        - waterfox-bin
        - custom-package
      default: 0
    validations:
      required: true

  - type: input
    id: custom_package
    attributes:
      label: Custom Package Name
      description: If you selected "custom-package" above, specify the package name here
      placeholder: e.g., "my-custom-app"
    validations:
      required: false

  - type: textarea
    id: reason
    attributes:
      label: Reason for Build
      description: Why do you need this package built? - keep it short as this becomes the title
      placeholder: e.g., "Shasums changed" or "Source file replaced"
    validations:
      required: true
