[openfoam]
source = 'cmd'
cmd = """
exit 1 # uncomment all lines to pull new version
#export GIT_TERMINAL_PROMPT=0
#for i in {12..40}; do 
#  git ls-remote \"https://github.com/OpenFOAM/OpenFOAM-$i.git\" &>/dev/null && 
#  LATEST=$i || break
#done && 
#git ls-remote --tags \"https://github.com/OpenFOAM/OpenFOAM-${LATEST}.git\" | 
#  grep -Eo 'tags/[0-9]{8}' | 
#  tail -n1 | 
#  sed 's/tags\\///' | 
#  awk \"{print \\\"${LATEST}.\\\" \\$1}\" | 
#  awk '{ print $0; if ($0 !~ /^[0-9]{2}[.][0-9]{8}$/) exit 1 }'
"""
