name: Arch Linux Task
on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  arch-task:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux

      - name: Update system and enable repositories
        run: |
          # Update pacman.conf to enable repos
          sed -i 's/^#\[extra\]/\[extra\]/' /etc/pacman.conf
          sed -i 's/^#\[community\]/\[community\]/' /etc/pacman.conf
          
          # Add development tools repository
          echo -e "\n[devel]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          
          # Update package database and system
          pacman -Syu --noconfirm

      - name: Install base development packages
        run: |
          pacman -S --noconfirm base-devel git

      - name: Run task
        run: |
          #!/bin/bash
          set -euo pipefail
          
          # Your task logic goes here
          echo "Starting task..."
          
          # Example environment setup
          export WORKDIR="/workspace"
          mkdir -p "$WORKDIR"
          cd "$WORKDIR"
          
          # Example task execution
          echo "Task executed at: $(date)"
          
          # Example error handling
          if [ $? -ne 0 ]; then
              echo "Task failed!"
              exit 1
          fi
          
          echo "Task completed successfully!"