name: Arch Linux Task
on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  arch-task:
  #  runs-on: ubuntu-latest
    runs-on: self-hosted
    container:
      image: archlinux:latest
      options: --privileged
    env:
        AUR_MAINTAINER_NAME: envolution
        GIT_USERNAME: envolution
        GIT_EMAIL: involution@gmail.com
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize pacman keyring
        run: |
          # Initialize keyring with proper permissions
          mkdir -p /etc/pacman.d/gnupg
          pacman-key --init
          pacman-key --populate archlinux
          echo -e "\n[multilib]" >> /etc/pacman.conf
          echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          cat /etc/pacman.conf

          # Update system and install dependencies
          pacman -Sy --noconfirm --needed archlinux-keyring
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git base-devel pacman-contrib \
            openssh github-cli jq expac ruby-rdoc ruby-pkg-config gnupg \
            pyalpm python-awesomeversion python-packaging python-lxml \
            python-jq python-gobject python-requests libnotify nvchecker \
            binutils

      - name: Setup non-root user for AUR
        run: |
          # Create build user with sudo access
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
          chmod 440 /etc/sudoers.d/builder

          # Create build directories with proper permissions
          install -d -m 755 /home/builder/.cache/paru
          install -d -m 755 /home/builder/.local/share/paru
          install -d -m 755 /home/builder/.gnupg
          chown -R builder:builder /home/builder

      - name: Install paru
        run: |
          cd /tmp
          sudo -u builder git clone https://aur.archlinux.org/paru-bin.git
          cd paru-bin
          sudo -u builder makepkg -si --noconfirm

          # Configure paru
          echo '[options]
          BatchInstall
          BottomUp
          RemoveMake
          SudoLoop
          UseAsk' | sudo tee /etc/paru.conf          

      - name: Setup SSH key
        run: |
          sudo -u builder mkdir -p /home/builder/.ssh
          sudo -u builder echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > /home/builder/.ssh/aur
          sudo -u builder ssh-keyscan aur.archlinux.org >> /home/builder/.ssh/known_hosts
          sudo -u builder cat /home/builder/.ssh/known_hosts
          sudo -u builder cat >> /home/builder/.ssh/config << EOF
          Host aur.archlinux.org
                IdentityFile /home/builder/.ssh/aur
                User aur
          EOF

      - name: Configure Git
        run: |
          sudo -u builder git config --global user.name "${{ env.GIT_USERNAME }}"
          sudo -u builder git config --global user.email "${{ env.GIT_EMAIL }}"          

      - name: Load NVChecker Script 
        run: |
          site_packages=$(python3 -c "import site; print('\n'.join(site.getsitepackages()))")
          [ -f ${GITHUB_WORKSPACE}/github-test.py ] && \
            cp ${GITHUB_WORKSPACE}/github-test.py ${site_packages}/nvchecker_source/

      - name: Run task
        run: |
          #!/bin/bash
          set -euo pipefail

          # Constants
          BUILDER_HOME="/home/builder"
          NVCHECKER_DIR="${BUILDER_HOME}/nvchecker"
          DEPENDS_JSON_PATH="/tmp/depends.json"

          # Helper Functions
          log_debug() {
              echo "[debug] $1"
          }

          log_error() {
              echo "[error] $1"
          }

          setup_environment() {
              sudo -u builder mkdir -p "${NVCHECKER_DIR}"
              cd "${NVCHECKER_DIR}"
              
              # Copy required Python scripts if they exist
              for script in "github_version.py" "compare_aur_local_versions.py"; do
                  if [ -f "${GITHUB_WORKSPACE}/${script}" ]; then
                      cp "${GITHUB_WORKSPACE}/${script}" "${NVCHECKER_DIR}"
                  fi
              done
          }

          generate_nvchecker_config() {
              local config_file="new.toml"
              
              # Create base config
              cat > "${config_file}" << EOF
          [__config__]
          oldver='aur.json'
          newver='local.json'

          EOF
              
              # Append all .nvchecker.toml files
              find "${GITHUB_WORKSPACE}" -name ".nvchecker.toml" -exec cat {} \; >> "${config_file}"
              
              log_debug "Generated ${config_file}:"
              cat "${config_file}"
          }

          run_version_checks() {
              local original_home=$HOME
              HOME="${BUILDER_HOME}"
              
              # Run nvchecker and generate comparison
              nvchecker -c new.toml --logger json > newver.json
              nvcmp -c new.toml
              
              HOME="${original_home}"
          }

          get_package_updates() {
              # Get upgrades from changes.json
              mapfile -t UPGRADES < <(jq -r 'to_entries | map(select(.value.status == "upgrade") | .key) | .[]' changes.json)
              log_debug "List of packages with UPGRADES scheduled from REPO -> AUR:"
              printf '%s\n' "${UPGRADES[@]}"
              
              # Get updates from nvchecker
              readarray -t NVCUPDATES < <(nvcmp -c new.toml -q)
              log_debug "List of packages in with UPGRADES scheduled from NVCHECKER:"
              printf '%s\n' "${NVCUPDATES[@]}"
              
              # Combine and deduplicate updates
              UPDATES=($(printf '%s\n' "${UPGRADES[@]}" "${NVCUPDATES[@]}" | sort -u))
          }

          extract_components() {
              local path="$1"
              IFS='/' read -r -a components <<< "${path:2}" # Remove leading './'
              echo "${components[@]}"
          }

          extract_dependencies() {
              local dir="$1"
              (
                  cd "$dir" || exit 1
                  source ./PKGBUILD
                  declare -p depends makedepends checkdepends 2>/dev/null || true
              )
          }

          process_package_dependencies() {
              local package="$1"
              local update_dir="$2"
              local depends_json="$3"
              
              # Extract dependencies
              local deps_output
              deps_output=$(extract_dependencies "${update_dir}")
              
              # Reset and evaluate dependency variables
              unset depends makedepends checkdepends
              eval "$deps_output"
              
              # Set default empty arrays if variables are unset
              depends=("${depends[@]:-}")
              makedepends=("${makedepends[@]:-}")
              checkdepends=("${checkdepends[@]:-}")
              
              # Convert to JSON
              echo "$depends_json" | jq \
                  --arg package "${package}" \
                  --argjson depends "$(printf '%s\n' "${depends[@]}" | jq -R . | jq -s .)" \
                  --argjson makedepends "$(printf '%s\n' "${makedepends[@]}" | jq -R . | jq -s .)" \
                  --argjson checkdepends "$(printf '%s\n' "${checkdepends[@]}" | jq -R . | jq -s .)" \
                  '.[$package] = {depends: $depends, makedepends: $makedepends, checkdepends: $checkdepends}'
          }

          build_package() {
              local package="$1"
              local build="$2"
              local pkgbuild="$3"
              
              log_debug "Building package: ${package}"
              
              sudo -u builder python buildscript.py \
                  --github-repo "${{ github.repository }}" \
                  --github-token "$GH_TOKEN" \
                  --github-workspace "$GITHUB_WORKSPACE" \
                  --package-name "$package" \
                  --pkgbuild-path "${pkgbuild}/${package}" \
                  --commit-message "Auto update: ${package}" \
                  --build-mode "$build" \
                  --debug
          }

          main() {
              setup_environment
              
              # Run initial version comparison
              python "${NVCHECKER_DIR}/compare_aur_local_versions.py" \
                  --maintainer "${AUR_MAINTAINER_NAME}" \
                  --repo-root "${GITHUB_WORKSPACE}"
              
              generate_nvchecker_config
              run_version_checks
              get_package_updates
              
              # Process dependencies for all updates
              depends_json="{}"
              for update in "${UPDATES[@]}"; do
                  subdirs=($(find . -maxdepth 3 -type d -name "${update}"))
                  
                  if [ ${#subdirs[@]} -ne 1 ]; then
                      log_debug "Skipping '${update}': found ${#subdirs[@]} matching directories"
                      continue
                  fi
                  
                  update_dir="${subdirs[0]}"
                  components=($(extract_components "${update_dir}"))
                  maintain="${components[0]:-}"
                  build="${components[1]:-}"
                  package="${components[2]:-}"
                  
                  if [ -z "$package" ] || [ -z "$build" ] || [ -z "$maintain" ]; then
                      log_error "Invalid directory structure for ${update_dir}"
                      continue
                  }
                  
                  depends_json=$(process_package_dependencies "$update" "$update_dir" "$depends_json")
              done
              
              # Save dependencies
              echo "${depends_json}" | jq . > "${DEPENDS_JSON_PATH}"
              
              # Build packages
              for update in "${UPDATES[@]}"; do
                  if ! build_package "$update" "$build" "$pkgbuild"; then
                      log_error "Build failed for ${update}"
                      continue
                  fi
              done
              
              log_debug "All updates processed successfully."
          }

          # Execute main function
          main "$@"          

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}