name: Arch Linux Task - Test A
on:
  workflow_dispatch:

jobs:
  arch-task:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    env:
        AUR_MAINTAINER_NAME: envolution
        GIT_USERNAME: envolution
        GIT_EMAIL: involution@gmail.com
        ACTIONS_STEP_SUMMARY: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#step:${{ github.job }}:markdown-summary
    steps:
      - name: Container Sanity Check
        shell: bash
        run: |
          echo "::notice title=Container Test::Inside archlinux container."
          echo "User: $(whoami)"
          echo "pwd: $(pwd)"
          echo "pacman --version"
          pacman --version || echo "pacman command not found or failed"
