name: Build with pacman and AUR cache
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u "+%Y-%m")" >> $GITHUB_OUTPUT

      - name: Cache pacman and AUR packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/pacman/pkg
            ~/.cache/paru
            ~/.local/share/paru
          key: ${{ runner.os }}-pacman-aur-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-pacman-aur-

      - name: Setup non-root user for AUR
        run: |
          # Create build user
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          # Create necessary directories with correct permissions
          install -d -m 755 /home/builder/.cache/paru
          install -d -m 755 /home/builder/.local/share/paru
          chown -R builder:builder /home/builder

      - name: Update system and install dependencies
        run: |
          # Initialize keyring
          pacman-key --init
          pacman-key --populate archlinux
          
          # Update package lists and system
          pacman -Sy --noconfirm archlinux-keyring
          pacman -Syu --noconfirm
          
          # Install git for paru
          pacman -S --noconfirm git

      - name: Install paru
        run: |
          cd /tmp
          git clone https://aur.archlinux.org/paru.git
          chown -R builder:builder paru
          cd paru
          sudo -u builder makepkg -si --noconfirm

      - name: Install mutter-git
        run: |
          # Install mutter-git using paru
          sudo -u builder paru -S --noconfirm mutter-git

      - name: Build
        uses: envolution/aur-release-action@v6.4

        with:
          package_name: gnome-shell-git # Use this if the package name in AUR is different from the repository name
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }} # The private SSH key to use to push the changes to the AUR
          github_token: ${{ secrets.GITHUB_TOKEN }} # The GitHub token to use to update the PKGBUILD file and the AUR submodule
          pkgbuild_path: gnome-shell-git/PKGBUILD # Use this if the PKGBUILD file is not in the root directory
          update_pkgbuild: false # Use this if you want to update the PKGBUILD in the main repository
          try_build_and_install: false # Use this if you want to try to build and install the package before publishing
          git_username: envolution # Use this if you want to change the git username (recommended)
          git_email: involution@gmail.com # Use this if you want to change the git email (recommended)
          commit_message: Auto Update # Use this if you want to change the commit message
          # prescript: scripts/pre.sh # Use this to run a script before building
          # postscript: scripts/post.sh # Use this if you want to run a script after the action makes changes, and finishes

