name: Arch Chroot Test

on:
  workflow_dispatch:

jobs:
  arch-chroot:
    runs-on: ubuntu-latest
    env:
      AUR_MAINTAINER_NAME: envolution
      GIT_USERNAME: envolution
      ROOT: /home/runner/work/aur/aur

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: "true"
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download Arch bootstrap
        run: |
          curl -sSLO https://iad.mirror.rackspace.com/archlinux/iso/latest/archlinux-bootstrap-x86_64.tar.zst
          tar --zstd -xf archlinux-bootstrap-x86_64.tar.zst --ignore-failed-read --warning=no-timestamp 2>/dev/null || true
          sudo mv root.x86_64 ${ROOT}/arch-root

      - name: Bind mounts
        run: |
          sudo mount --bind ${ROOT}/arch-root ${ROOT}/arch-root
          sudo mount --bind /dev ${ROOT}/arch-root/dev
          sudo mount --bind /proc ${ROOT}/arch-root/proc
          sudo mount --bind /sys ${ROOT}/arch-root/sys
          sudo mount --bind /run ${ROOT}/arch-root/run

      - name: Build
        run: |
          echo "Free space:"
          df -h
          ls -la ${ROOT}

      - name: Test pacman
        run: |
          sudo chroot ${ROOT}/arch-root /bin/bash -c "
          echo ${GIT_USERNAME}
          echo 'Free space:'
          df -h
          "

      - name: Cleanup mounts
        if: always()
        run: |
          sudo umount ${ROOT}/arch-root/dev || true
          sudo umount ${ROOT}/arch-root/proc || true
          sudo umount ${ROOT}/arch-root/sys || true
